popvm_op_sources = \
	$(top_srcdir)/popvm/ops/op_hlt.c \
	$(top_srcdir)/popvm/ops/op_nop.c \
	$(top_srcdir)/popvm/ops/op_push.c \
	$(top_srcdir)/popvm/ops/op_pop.c \
	$(top_srcdir)/popvm/ops/op_dup.c \
	$(top_srcdir)/popvm/ops/op_dup2.c \
	$(top_srcdir)/popvm/ops/op_swap.c \
	$(top_srcdir)/popvm/ops/op_clsr.c \
	$(top_srcdir)/popvm/ops/op_oenv.c \
	$(top_srcdir)/popvm/ops/op_cenv.c \
	$(top_srcdir)/popvm/ops/op_bind.c \
	$(top_srcdir)/popvm/ops/op_lkup.c \
	$(top_srcdir)/popvm/ops/op_jmp.c \
	$(top_srcdir)/popvm/ops/op_jt.c \
	$(top_srcdir)/popvm/ops/op_jf.c \
	$(top_srcdir)/popvm/ops/op_call.c \
	$(top_srcdir)/popvm/ops/op_ret.c \
	$(top_srcdir)/popvm/ops/op_pos.c \
	$(top_srcdir)/popvm/ops/op_neg.c \
	$(top_srcdir)/popvm/ops/op_not.c \
	$(top_srcdir)/popvm/ops/op_cmpl.c \
	$(top_srcdir)/popvm/ops/op_inc.c \
	$(top_srcdir)/popvm/ops/op_dec.c \
	$(top_srcdir)/popvm/ops/op_add.c \
	$(top_srcdir)/popvm/ops/op_sub.c \
	$(top_srcdir)/popvm/ops/op_mul.c \
	$(top_srcdir)/popvm/ops/op_div.c \
	$(top_srcdir)/popvm/ops/op_mod.c \
	$(top_srcdir)/popvm/ops/op_lsh.c \
	$(top_srcdir)/popvm/ops/op_rsh.c \
	$(top_srcdir)/popvm/ops/op_land.c \
	$(top_srcdir)/popvm/ops/op_lor.c \
	$(top_srcdir)/popvm/ops/op_and.c \
	$(top_srcdir)/popvm/ops/op_or.c \
	$(top_srcdir)/popvm/ops/op_xor.c \
	$(top_srcdir)/popvm/ops/op_lt.c \
	$(top_srcdir)/popvm/ops/op_gt.c \
	$(top_srcdir)/popvm/ops/op_le.c \
	$(top_srcdir)/popvm/ops/op_ge.c \
	$(top_srcdir)/popvm/ops/op_eq.c \
	$(top_srcdir)/popvm/ops/op_ne.c \
	$(top_srcdir)/popvm/ops/op_idx.c \
	$(top_srcdir)/popvm/ops/op_mem.c \
	$(top_srcdir)/popvm/ops/op_lbl.c \
	$(top_srcdir)/popvm/ops/op_com.c \
	$(top_srcdir)/popvm/ops/op_line.c
